version: "3"

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    volumes:
      - ./src:/code
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    ports:
      - "3308:3308"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:89"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel